#!/usr/bin/python3
"""
This module returns the perimeter of the island described in grid
"""


def island_perimeter(grid):
    """
    Function that decribes a grid and returns
    the perimeter of the island described
    """
    perimeter = 0
    for i in range(len(grid)):
        for j in range(len(grid[0])):
            if grid[i][j] == 1:
                perimeter += 4
                if i > 0 and grid[i - j][j] == 1:
                    perimeter -= 2
                if j > 0 and grid[i][j - i] == 1:
                    perimeter -= 2
    return perimeter
